### ISSUE TITLE
Does not work with Sentry

### ISSUE THREAD

**Issue by newtonianb** [darsain/laravel-console#12]
The login process throws an error with Sentry and Console
https://github.com/cartalyst/sentry
This error dissapears when you remove this line in your app.php
`'Darsain\Console\ConsoleServiceProvider',`

```
"error":{"type":"ErrorException","message":"PDO::quote() expects parameter 1 to be string, object given","file":"vendor\\darsain\\console\\src\\models\\console.php","line":44}}
```

**Comment by darsain** [comment]
What version of Laravel, and what version of Console are you using?

**Comment by newtonianb** [comment]
Laravel 4
"darsain/console": "dev-master"
"url":  "git://github.com/allmyitjason/laravel-console.git" 

And the update on dev-master is from yesterday

**Comment by newtonianb** [comment]
It fails at line

```
$credentials = array(
        'email'    => Input::get('user_email'),
        'password' => Input::get('user_password')
      );
$user = Sentry::authenticate($credentials, false);
```

**Comment by darsain** [comment]
That is a fork of this repo residing at http://github.com/allmyitjason/laravel-console

I haven't accepted that PR because there have been some issues with it, and also I wanted to do some re-factoring, which I did.

Anyway, there is no Console for L4 from me yet :) Here is more about the issue: https://github.com/Darsain/laravel-console/pull/11#issuecomment-21403584

**Comment by newtonianb** [comment]
I see. Any eta when you'll release for version 4? It's great!
