### ISSUE TITLE
Is there a way I can add profiler to console

### ISSUE THREAD

**Issue by markwu** [darsain/laravel-console#4]
Hi Darsain:

Thanks for this bundle. I really like it and always use it when I test model.

I just wondering is there any way I can add Laravel profiler to console, So I can see my query, log, time, etc.

Mark

**Comment by darsain** [comment]
No. I can't include Laravels profiler in the response, as I'd have to do some weird hacking to change Response::ajax() state to false (otherwise Profiler won't render anything), than do some pain in the ass CSS hacking so it would display correctly in the UI,... those are some dirty things I really don't want to go trough.

That being said, I acknowledge that a list of executed SQL queries with their execution time would be helpful, so I'm creating an issue for this. Can't give you any ETA though. I'm not working on anything PHP related at the moment, so I don't know when I'll get to it.

**Comment by markwu** [comment]
I read the source code last night, and  came to the same conclusion. Anyway, still thanks!

Mark
